### PR TITLE
BI-1680 - Added Migration That Removes "Somoclone" Breeding Method

### PR DESCRIPTION
**Pull request by mlm483**
# Description
**Story:** [BI-1680](https://breedinginsight.atlassian.net/browse/BI-1680)

Per the **Desired Behavior** section of the Jira story, I added a migration to remove the "Somoclone" breeding method from the system preset breeding methods.

This [bi-web PR](https://github.com/Breeding-Insight/bi-web/pull/370) takes care of updating the import template.

# Dependencies
bi-web branch: `feature/BI-1680`.
# Testing
1. Checkout this branch, `git checkout feature/BI-1680`.
2. Run bi-api.
3. Ensure that the new migration ran (V1.20.0) by checking the bidb database, `SELECT * FROM flyway_schema_history;`.
4. Ensure that the "Somoclone" breeding method is not listed in the DeltaBreed UI, under **Program Administration > Breeding Methods**.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

[BI-1680]: https://breedinginsight.atlassian.net/browse/BI-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by davedrp** [comment]
when the migration was run, the following error was generated...
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:7.7.3:migrate (default-cli) on project bi-api: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
[ERROR] Migration V1.21.0__remove_breeding_method.sql failed
[ERROR] ----------------------------------------------------
[ERROR] SQL State  : 23503
[ERROR] Error Code : 0
[ERROR] Message    : ERROR: update or delete on table "breeding_method" violates foreign key constraint "program_enabled_breeding_methods_breeding_method_id_fkey" on table "program_enabled_breeding_methods"
[ERROR]   Detail: Key (id)=(20811b55-6080-459f-aca4-261fb1c95c60) is still referenced from table "program_enabled_breeding_methods".
[ERROR]   Where: SQL statement "DELETE FROM breeding_method
[ERROR]     WHERE abbreviation = 'SOC' AND name = 'Somoclone'"
[ERROR] PL/pgSQL function inline_code_block line 4 at SQL statement
[ERROR] Location   : /Users/drp227/source/bi-api/src/main/resources/db/migration/V1.21.0__remove_breeding_method.sql (/Users/drp227/source/bi-api/src/main/resources/db/migration/V1.21.0__remove_breeding_method.sql)
[ERROR] Line       : 18
[ERROR] Statement  : /*

**Review by davedrp — APPROVED** [review]
Passeed Developer test.

**Review by davedrp — APPROVED** [review]
Passed Developer testing

**Comment by mlm483** [comment]
Closing in favor of https://github.com/Breeding-Insight/bi-api/pull/346, which is based on release/0.9.

**Pull request closed without merging**
