### PR TITLE
BI-2227 - Modify Upload Experiment and Observations File to accept without sub units

### PR DESCRIPTION
**Pull request by nickpalladino**
# Description
**Story:** [BI-2227](https://breedinginsight.atlassian.net/browse/BI-2227?atlOrigin=eyJpIjoiMzM4ZDlkMDA4NTYzNGQwOGE3YTU2N2M1ZWFkMzk1NjQiLCJwIjoiaiJ9)

- db migration to remove subentity columns from exp import template

# Dependencies
- bi-web BI-2226

# Testing
- Get error when old subentity columns are included
- Using new template without subentity columns should import without issue

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [x] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<please include a link to TAF run>_

[BI-2227]: https://breedinginsight.atlassian.net/browse/BI-2227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nickpalladino** [comment]
Looks like I need to fix some tests

**Comment by nickpalladino** [comment]
tests fixed

**Review by HMS17 — CHANGES_REQUESTED** [review]
BI-2283 uses V1.27.0 for its migration V1.27.0__fix_fk_constraint.sql, so the migration number would need to be changed here

**Review by dmeidlin — APPROVED** [review]

**Comment by nickpalladino** [comment]
@HMS17 Renamed migration

**Review by HMS17 — APPROVED** [review]
Passed test!

**Pull request merged**
